- hosts: all  
  become: true
  tasks:
   - name: install Docker ##installing docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker ##starting docker service
     service:
       name: docker
       state: started

   - name: disable SELinux ##disabling SELinux as it is not fully supported by kubernetes
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1 ##setting up IPTables for networking
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository ##adding kubernetes YUM repository in remote server' repository list
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet ##installing kubelet
     yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

   - name: install kubeadm ##installing kubeadm
     yum:
        name: kubeadm-1.14.0
        state: present

   - name: start kubelet #starting kubelet service
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl ##installing kubectl on master node
     yum:
        name: kubectl-1.14.0
        state: present
        allow_downgrade: yes
